name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-XX-XX-XX-XX.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-XX-XX-XX-XX.compute.amazonaws.com << 'EOF'
            cd ~/simple-node-app || git clone https://github.com/TU_USUARIO/simple-node-app.git && cd simple-node-app
            git pull origin main
            npm install
            pm2 reload ecosystem.config.js
          EOF
